## 1) 회귀 모델
Keras 간단한 회귀 모델 예제

x = [1, 2, 3, 4, 5, 6, 7, 8, 9]  
y = [1, 4, 9, 16, 25, 36, 49, 64, 81]  

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# 데이터 준비
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=float)
y = np.array([1, 4, 9, 16, 25, 36, 49, 64, 81], dtype=float)

# 모델 구성
model = keras.Sequential([
    layers.Dense(1, input_shape=[1])  # 선형 레이어 하나를 사용
])

# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error')

# 모델 학습
hist = model.fit(x, y, epochs=100)



Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 1613.4598
Epoch 2/100
1/1 [==============================] - 0s 23ms/step - loss: 1612.9615
Epoch 3/100
1/1 [==============================] - 0s 19ms/step - loss: 1612.4634
Epoch 4/100
1/1 [==============================] - 0s 21ms/step - loss: 1611.9651
Epoch 5/100
1/1 [==============================] - 0s 22ms/step - loss: 1611.4669
Epoch 6/100
1/1 [==============================] - 0s 19ms/step - loss: 1610.9690
Epoch 7/100
1/1 [==============================] - 0s 20ms/step - loss: 1610.4711
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 1609.9731
Epoch 9/100
1/1 [==============================] - 0s 12ms/step - loss: 1609.4755
Epoch 10/100
1/1 [==============================] - 0s 19ms/step - loss: 1608.9779
Epoch 11/100
1/1 [==============================] - 0s 15ms/step - loss: 1608.4803
Epoch 12/100
1/1 [==============================] - 0s 11ms/step - loss: 1607.9829
Epoch 13/100
1/

In [2]:
# 학습된 모델로 예측
predicted_y = model.predict([10, 20])
predicted_y

1/1 [==============================] - 0s 130ms/step


array([[3.130508],
       [6.16135 ]], dtype=float32)

In [8]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# 데이터 준비
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=float)
y = np.array([1, 4, 9, 16, 25, 36, 49, 64, 81], dtype=float)

# 모델 구성
model = keras.Sequential([
    layers.Dense(20, input_shape=[1]),  # 선형 레이어 20 를 사용
    layers.Dense(1)
])

# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error')

# 모델 학습
hist = model.fit(x, y, epochs=1000, verbose=0)
# 학습된 모델로 예측
predicted_y = model.predict([10, 20])
predicted_y

1/1 [==============================] - 0s 64ms/step


array([[ 68.66511],
       [134.92682]], dtype=float32)

## 2) 이진 분류 모델

Keras사용해서 2진 분류 모델

x = [[0, 0], [-1, -4], [-10, -50], [0, -10], [10, 20], [3,4], [9, 50]]    
y = [0, 0, 0, 0, 1, 1, 1]  

In [9]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split

# 데이터 준비
x = np.array([[0, 0], [-1, -4], [-10, -50], [0, -10], [10, 20], [3, 4], [9, 50]])
y = np.array([0, 0, 0, 0, 1, 1, 1])

# 모델 생성
model = keras.Sequential([
    keras.layers.Input(shape=(2,)),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

# 모델 컴파일
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 모델 훈련
model.fit(x, y, epochs=100, verbose=0)

In [5]:
# 모델 평가
model.predict([[-1, -1], [30, 10]]) # [0, 1]

1/1 [==============================] - 0s 64ms/step


array([[0.39982122],
       [0.99983263]], dtype=float32)

## 3) 다중 분류 모델

Keras 다중 분류 모델

x = [[0, 0], [-1, -4], [-10, -50], [0, -10], [10, 20], [3,4], [9, 50], [100, 200], [500, 200], [300,100]]    
y = [1, 1, 1, 1, 2, 2, 2, 3, 3, 3]  

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

# 데이터 준비
x = np.array([[0, 0], [-1, -4], [-10, -50], [0, -10], [10, 20], [3, 4], [9, 50], [100, 200], [500, 200], [300, 100]])
y = np.array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2])

# 데이터 전처리
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

encoder = OneHotEncoder(sparse=False)
y_encoded = encoder.fit_transform(y.reshape(-1, 1))

# 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2, random_state=42)

# 모델 생성
model = keras.Sequential([
    keras.layers.Input(shape=(2,)),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(3, activation='softmax')
])

# 모델 컴파일
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# 모델 훈련
hist = model.fit(x_train, y_train, epochs=100, verbose=0)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [7]:
model.predict([[10, 20], [100, 200]])

1/1 [==============================] - 0s 68ms/step


array([[3.0624676e-22, 1.9212308e-29, 1.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00]], dtype=float32)